name: correr test de Cypress
on:
    push:

jobs:
    eslint:
        runs-on: ubuntu-22.04
        name: static analysis
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npm run lints